"""users table

Revision ID: 491478389384
Revises: 
Create Date: 2023-03-08 23:56:50.431775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '491478389384'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index('idx_retdate')
        batch_op.drop_index('idx_stock')

    op.drop_table('returns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returns',
    sa.Column('stock', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('returndate', mysql.DATETIME(), nullable=False),
    sa.Column('returns', mysql.DECIMAL(precision=15, scale=13), nullable=True),
    sa.PrimaryKeyConstraint('stock', 'returndate'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.create_index('idx_stock', ['stock'], unique=False)
        batch_op.create_index('idx_retdate', ['returndate'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
