"""users table

Revision ID: b6d09c466119
Revises: 491478389384
Create Date: 2023-03-09 10:21:18.967703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6d09c466119'
down_revision = '491478389384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('returns',
               existing_type=mysql.DECIMAL(precision=15, scale=13),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index('idx_retdate')
        batch_op.drop_index('idx_stock')
        batch_op.create_index(batch_op.f('ix_returns_returndate'), ['returndate'], unique=False)
        batch_op.create_index(batch_op.f('ix_returns_stock'), ['stock'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_returns_stock'))
        batch_op.drop_index(batch_op.f('ix_returns_returndate'))
        batch_op.create_index('idx_stock', ['stock'], unique=False)
        batch_op.create_index('idx_retdate', ['returndate'], unique=False)
        batch_op.alter_column('returns',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=15, scale=13),
               existing_nullable=True)
        batch_op.alter_column('stock',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
